### ISSUE TITLE
Facing issue in latest release - nix-clap@1.0.8

### ISSUE THREAD

**Issue by srikanthkolli** [jchip/nix-clap#2]
Error at the **\nix-clap\lib\nix-clap.js:7** 
```
const { objEach, makeDefaults, applyDefaults } = require("./xtil");
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\myproject\node_modules\xclap\cli\nix-clap.js:5:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

```

**Comment by jchip** [comment]
you need NodeJS v6 and up

**Comment by jchip** [comment]
1.0.9 works with node 4
